// ═══════════════════════════════════════════════════════════
//  TRIP DATA  —  edit this file to update the website
//  After editing: save, commit & push to GitHub
//
//  For each translatable field there is a matching _zh field.
//  Names of participants are NEVER translated.
// ═══════════════════════════════════════════════════════════

const TRIP = {

  // ── General info ──────────────────────────────────────────
  name:       "Xi'an Family Trip",
  name_zh:    "西安家庭之旅",

  dates:      "April 1–7, 2025",
  dates_zh:   "2025年4月1日–7日",

  tagline:    "7 family members · 7 days · history & adventure",
  tagline_zh: "7位家庭成员 · 7天 · 历史与探险",

  // ── Organizer password ────────────────────────────────────
  password: "xian2025",

  // ── Participants ──────────────────────────────────────────
  //  name is never translated
  //  role / role_zh : English and Chinese role labels
  participants: [
    { id:"p1", emoji:"👴", name:"Opa",        role:"Grandfather", role_zh:"爷爷", days:["d1","d2","d3","d4","d5","d6","d7"] },
    { id:"p2", emoji:"👵", name:"Oma",        role:"Grandmother", role_zh:"奶奶", days:["d1","d2","d3","d4","d5","d6","d7"] },
    { id:"p3", emoji:"⛰️", name:"Yisen 屹森", role:"Guest",       role_zh:"嘉宾", days:["d1","d2","d3","d4","d5","d6","d7"] },
    { id:"p4", emoji:"🌸", name:"Fei 菲",     role:"Guest",       role_zh:"嘉宾", days:["d1","d2","d3","d4","d5","d6"] },
    { id:"p5", emoji:"🌲", name:"Sjoerd 大树",role:"Guest",       role_zh:"嘉宾", days:["d1","d2","d3","d4","d5","d6","d7"] },
    { id:"p6", emoji:"👵", name:"姥姥",       role:"Grandmother", role_zh:"姥姥", days:["d1","d2","d3","d4","d5","d6","d7"] },
    { id:"p7", emoji:"👴", name:"老爷",       role:"Grandfather", role_zh:"老爷", days:["d1","d2","d3","d4","d5","d6","d7"] },
  ],

  // ── Days ──────────────────────────────────────────────────
  days: [

    // ── DAY 1 ────────────────────────────────────────────────
    {
      id:"d1",
      date:"Tuesday 1 April",  date_zh:"4月1日 周二",
      theme:"Beijing → Xi'an", theme_zh:"北京 → 西安",
      start:"08:30",
      desc:"We leave home early and take the high-speed train to Xi'an. A long travel day — settle in and enjoy the scenery from the window.",
      desc_zh:"一早离家，乘坐高铁前往西安。今天以旅途为主，放松心情欣赏沿途窗外风景。",
      events:[
        { id:"e1",  time:"08:30", type:"drive",
          title:"Leave home",                              title_zh:"出发离家",
          desc:"Head to Beijing station together. Allow extra time for Opa, Oma, 姥姥 & 老爷.",
          desc_zh:"大家一同出发前往北京站，请为爷爷、奶奶、姥姥和老爷预留充裕时间。",
          who:[] },
        { id:"e2",  time:"10:00", type:"drive",
          title:"High-speed train departs — Beijing to Xi'an", title_zh:"高铁出发——北京至西安",
          desc:"Journey is approximately 4.5 hours. Snacks and drinks available on board.",
          desc_zh:"全程约4.5小时，车上可购买零食和饮料。",
          who:[] },
        { id:"e3",  time:"14:30", type:"drive",
          title:"Arrive Xi'an — transfer to hotel",        title_zh:"抵达西安——前往酒店",
          desc:"Estimated arrival. Take taxi or arranged transfer from Xi'an North station.",
          desc_zh:"预计抵达时间。从西安北站乘坐出租车或预约接送前往酒店。",
          who:[] },
        { id:"e4",  time:"16:00", type:"stay",
          title:"Check in & rest",                         title_zh:"入住酒店，休息整顿",
          desc:"Freshen up and rest after the long journey.",
          desc_zh:"旅途后梳洗休整。",
          who:[] },
        { id:"e5",  time:"19:00", type:"food",
          title:"Welcome dinner — Muslim Quarter",         title_zh:"欢迎晚餐——回民街",
          desc:"Xi'an's famous street food strip. Try the rou jia mo, lamb skewers, and cold noodles.",
          desc_zh:"西安著名的回民街小吃一条街，必试肉夹馍、烤羊肉串和凉皮。",
          who:[] },
      ],
    },

    // ── DAY 2 ────────────────────────────────────────────────
    {
      id:"d2",
      date:"Wednesday 2 April",  date_zh:"4月2日 周三",
      theme:"Terracotta Army",   theme_zh:"秦始皇兵马俑",
      start:"09:00",
      desc:"Today we visit one of the greatest archaeological discoveries in the world — the Mausoleum of Qin Shi Huang and the famous Terracotta Army.",
      desc_zh:"今天参观世界上最伟大的考古发现之一——秦始皇陵及举世闻名的兵马俑。",
      events:[
        { id:"e6",  time:"08:00", type:"food",
          title:"Breakfast at hotel",                      title_zh:"酒店早餐",
          desc:"Included in booking. Early start today.",
          desc_zh:"早餐含在住宿费用内，今天出发较早。",
          who:[] },
        { id:"e7",  time:"09:00", type:"drive",
          title:"Depart to Qin Shi Huang Mausoleum",       title_zh:"出发前往秦始皇陵",
          desc:"About 40 minutes from the city centre by taxi or tour bus.",
          desc_zh:"从市中心乘出租车或旅游巴士约40分钟。",
          who:[] },
        { id:"e8",  time:"10:00", type:"activity",
          title:"Qin Shi Huang Mausoleum & Terracotta Army", title_zh:"秦始皇陵及兵马俑",
          desc:"Explore Pits 1, 2, and 3. Allow at least 3 hours. Wheelchair-accessible paths available for Opa, Oma, 姥姥 & 老爷.",
          desc_zh:"参观一号坑、二号坑和三号坑，至少预留3小时。景区内有无障碍通道，方便爷爷、奶奶、姥姥和老爷出行。",
          who:[] },
        { id:"e9",  time:"13:30", type:"food",
          title:"Lunch near the museum",                   title_zh:"博物馆附近午餐",
          desc:"Several restaurants near the entrance. Try the local hand-pulled noodles.",
          desc_zh:"入口附近有多家餐厅，推荐尝试当地手擀面。",
          who:[] },
        { id:"e10", time:"15:00", type:"activity",
          title:"Huaqing Hot Springs (optional)",          title_zh:"华清宫温泉（可选）",
          desc:"A short detour on the way back — beautiful imperial gardens and historic hot spring pools.",
          desc_zh:"返程途中的小绕道——美丽的皇家园林与历史悠久的温泉浴池。",
          who:[] },
        { id:"e11", time:"19:00", type:"food",
          title:"Dinner — Defachang Dumpling Banquet",     title_zh:"晚餐——德发长饺子宴",
          desc:"Xi'an's famous dumpling banquet. Over 20 different shapes and fillings. Book ahead.",
          desc_zh:"西安著名的饺子宴，多达20余种造型与馅料，建议提前预订。",
          who:[] },
      ],
    },

    // ── DAY 3 ────────────────────────────────────────────────
    {
      id:"d3",
      date:"Thursday 3 April",                  date_zh:"4月3日 周四",
      theme:"Huashan Mountain & Evening Show",   theme_zh:"华山 & 晚间演出",
      start:"07:00",
      desc:"An adventurous day at one of China's Five Sacred Mountains — Huashan. In the evening we return to the city for a spectacular cultural show.",
      desc_zh:"在中国五岳之一的华山度过充满冒险的一天，傍晚返回城市欣赏精彩文艺演出。",
      events:[
        { id:"e12", time:"07:00", type:"food",
          title:"Early breakfast",                         title_zh:"早起用早餐",
          desc:"Early start for Huashan. Fuel up well!",
          desc_zh:"前往华山出发早，请吃饱喝足！",
          who:[] },
        { id:"e13", time:"07:30", type:"drive",
          title:"Depart to Huashan",                       title_zh:"出发前往华山",
          desc:"About 1.5 hours by car or train. Note: Huashan involves steep climbing — Opa, Oma, 姥姥 & 老爷 are recommended to take the cable car and enjoy the scenic lower trails.",
          desc_zh:"乘车或火车约1.5小时。提示：华山爬山坡度较大，建议爷爷、奶奶、姥姥和老爷乘坐缆车并游览山下风景步道。",
          who:[] },
        { id:"e14", time:"09:00", type:"activity",
          title:"Huashan Mountain",                        title_zh:"华山游览",
          desc:"Choose your route based on fitness. North Peak is accessible by cable car. South, West & East Peaks for the more adventurous. The famous Plank Walk is strictly optional!",
          desc_zh:"根据体力选择路线。北峰可乘缆车直达，南峰、西峰和东峰适合体力充沛者。著名的长空栈道纯属自愿挑战！",
          who:[] },
        { id:"e15", time:"13:00", type:"food",
          title:"Lunch on the mountain",                   title_zh:"山上午餐",
          desc:"Simple noodles and hot food available at mountain restaurants.",
          desc_zh:"山上餐厅提供简单面食与热菜。",
          who:[] },
        { id:"e16", time:"16:00", type:"drive",
          title:"Return to Xi'an",                         title_zh:"返回西安",
          desc:"Head back to the city in time to rest before the evening show.",
          desc_zh:"返回市区，在晚间演出前稍作休息。",
          who:[] },
        { id:"e17", time:"20:00", type:"activity",
          title:"Tang Dynasty Music & Dance Show",         title_zh:"唐代乐舞演出",
          desc:"A spectacular show recreating the golden age of the Tang Dynasty with traditional costumes, music, and dance.",
          desc_zh:"一场重现盛唐辉煌的精彩演出，融合传统服饰、音乐与舞蹈。",
          who:[] },
      ],
    },

    // ── DAY 4 ────────────────────────────────────────────────
    {
      id:"d4",
      date:"Friday 4 April",               date_zh:"4月4日 周五",
      theme:"Xi'an City Walls & Old Town",  theme_zh:"西安城墙与老城区",
      start:"09:00",
      desc:"A day to explore Xi'an's magnificent ancient city walls — the best preserved in China — and the historic streets of the old town.",
      desc_zh:"今天探索西安宏伟的古城墙——中国保存最完好的城墙——以及老城区的历史街巷。",
      events:[
        { id:"e18", time:"08:00", type:"food",
          title:"Breakfast at hotel",                      title_zh:"酒店早餐",
          desc:"",  desc_zh:"",
          who:[] },
        { id:"e19", time:"09:00", type:"activity",
          title:"Xi'an City Wall",                         title_zh:"西安城墙",
          desc:"Rent bikes and cycle the full 14km loop on top of the walls — or take the electric cart for Opa, Oma, 姥姥 & 老爷. Fantastic views over the city.",
          desc_zh:"可租自行车骑行完整的14公里城墙环路，或为爷爷、奶奶、姥姥和老爷选乘电瓶车。俯瞰全城的景色令人叹为观止。",
          who:[] },
        { id:"e20", time:"12:00", type:"food",
          title:"Lunch — Yongxingfang Food Street",        title_zh:"午餐——永兴坊美食街",
          desc:"A great indoor food market with Xi'an classics. Must-try: biangbiang noodles.",
          desc_zh:"汇聚西安经典美食的室内美食广场，必点biangbiang面。",
          who:[] },
        { id:"e21", time:"14:00", type:"activity",
          title:"Shaanxi History Museum",                  title_zh:"陕西历史博物馆",
          desc:"One of China's finest museums. Free entry with passport. Allow 2–3 hours. Flat and accessible throughout.",
          desc_zh:"中国顶级博物馆之一，凭护照免费入场，参观约需2–3小时，全馆无障碍通行。",
          who:[] },
        { id:"e22", time:"18:00", type:"activity",
          title:"Bell Tower & Drum Tower at dusk",         title_zh:"傍晚游览钟楼与鼓楼",
          desc:"Beautiful at sunset. Watch the drum performance at the Drum Tower.",
          desc_zh:"日落时分景色绝美，可在鼓楼欣赏击鼓表演。",
          who:[] },
        { id:"e23", time:"19:30", type:"food",
          title:"Dinner — Muslim Quarter",                 title_zh:"晚餐——回民街",
          desc:"Back to the Muslim Quarter for more street food. Take your time and try different stalls.",
          desc_zh:"再度光顾回民街，慢慢品味各摊位的特色小吃。",
          who:[] },
      ],
    },

    // ── DAY 5 ────────────────────────────────────────────────
    {
      id:"d5",
      date:"Saturday 5 April",              date_zh:"4月5日 周六",
      theme:"Xi'an — temples & free time",  theme_zh:"西安——寺庙与自由时光",
      start:"09:00",
      desc:"A slightly more relaxed day. Key sights in the morning, free afternoon for shopping, rest, or exploring at your own pace.",
      desc_zh:"今天节奏稍慢，上午游览重点景点，下午自由安排购物、休息或自行探索。",
      events:[
        { id:"e24", time:"08:00", type:"food",
          title:"Breakfast at hotel",                      title_zh:"酒店早餐",
          desc:"",  desc_zh:"",
          who:[] },
        { id:"e25", time:"09:00", type:"activity",
          title:"Wild Goose Pagoda & Daci'en Temple",      title_zh:"大雁塔与大慈恩寺",
          desc:"An iconic Xi'an landmark. The pagoda dates to 652 AD. Beautiful temple grounds with easy walking paths for everyone.",
          desc_zh:"西安标志性建筑，大雁塔建于公元652年，寺院环境优美，步道平坦适合各年龄层。",
          who:[] },
        { id:"e26", time:"11:30", type:"activity",
          title:"Xingjiao Temple (optional)",              title_zh:"兴教寺（可选）",
          desc:"Quiet temple on the outskirts of the city, associated with the monk Xuanzang of Journey to the West.",
          desc_zh:"位于城郊的清幽古寺，与《西游记》中的玄奘法师渊源深厚。",
          who:[] },
        { id:"e27", time:"13:00", type:"food",
          title:"Lunch — local restaurant",                title_zh:"午餐——当地餐厅",
          desc:"Ask the hotel for a recommendation.",
          desc_zh:"可向酒店前台询问推荐餐厅。",
          who:[] },
        { id:"e28", time:"14:30", type:"free",
          title:"Free afternoon",                          title_zh:"自由下午",
          desc:"Shopping on Dong Dajie, rest at the hotel, or explore the old city lanes at your own leisure.",
          desc_zh:"可在东大街购物，在酒店休息，或悠闲漫步老城小巷。",
          who:[] },
        { id:"e29", time:"19:00", type:"food",
          title:"Group dinner",                            title_zh:"团体晚餐",
          desc:"Full group dinner — enjoy every moment together!",
          desc_zh:"全员共进晚餐——珍惜每一刻相聚时光！",
          who:[] },
      ],
    },

    // ── DAY 6 ────────────────────────────────────────────────
    {
      id:"d6",
      date:"Sunday 6 April",        date_zh:"4月6日 周日",
      theme:"Last day in Xi'an",    theme_zh:"西安最后一天",
      start:"09:00",
      desc:"Our last full day in Xi'an. Fei 菲 departs in the evening — we make the most of the day together before saying goodbye.",
      desc_zh:"在西安的最后一整天。菲傍晚离开——大家珍惜在一起的时光，依依惜别。",
      events:[
        { id:"e30", time:"08:00", type:"food",
          title:"Breakfast at hotel",                      title_zh:"酒店早餐",
          desc:"",  desc_zh:"",
          who:[] },
        { id:"e31", time:"09:00", type:"activity",
          title:"City wall — morning stroll",              title_zh:"城墙晨间漫步",
          desc:"A relaxed second visit to the city walls at an easy pace.",
          desc_zh:"再次登上城墙，以悠闲的步伐享受清晨时光。",
          who:[] },
        { id:"e32", time:"11:00", type:"activity",
          title:"Souvenirs & last-minute shopping",        title_zh:"纪念品与最后购物",
          desc:"Pick up shadow puppets, terracotta replicas, local tea, or silk scarves.",
          desc_zh:"选购皮影偶、兵马俑复制品、当地茶叶或丝巾作为留念。",
          who:[] },
        { id:"e33", time:"13:00", type:"food",
          title:"Lunch together",                          title_zh:"共进午餐",
          desc:"Last meal all together as a group.",
          desc_zh:"全员共进的最后一顿午餐。",
          who:[] },
        { id:"e34", time:"14:00", type:"free",
          title:"Free afternoon — rest & pack",            title_zh:"自由下午——休息与整理行李",
          desc:"Rest, pack, or a final wander through the streets.",
          desc_zh:"休息整理行李，或最后漫步街头。",
          who:[] },
        { id:"e35", time:"18:00", type:"drive",
          title:"Fei 菲 departs to the airport",           title_zh:"菲出发前往机场",
          desc:"Safe travels, Fei! Xi'an Xianyang International Airport is about 45 minutes from the city centre.",
          desc_zh:"一路顺风，菲！西安咸阳国际机场距市中心约45分钟车程。",
          who:["p4"] },
        { id:"e36", time:"19:30", type:"food",
          title:"Dinner — remaining group",                title_zh:"晚餐——其余成员",
          desc:"A quiet dinner for those still in Xi'an.",
          desc_zh:"留守西安的成员共进温馨晚餐。",
          who:["p1","p2","p3","p5","p6","p7"] },
      ],
    },

    // ── DAY 7 ────────────────────────────────────────────────
    {
      id:"d7",
      date:"Monday 7 April",              date_zh:"4月7日 周一",
      theme:"Xi'an → Beijing — home",     theme_zh:"西安 → 北京——回家",
      start:"10:00",
      desc:"Last morning in Xi'an. Checkout by 10:00, then to the station for the train home. A wonderful week — safe travels everyone!",
      desc_zh:"在西安的最后一个早晨。10:00前退房，前往火车站踏上归途。美好的一周——大家一路平安！",
      events:[
        { id:"e37", time:"08:00", type:"food",
          title:"Final breakfast at hotel",                title_zh:"酒店告别早餐",
          desc:"Checkout by 10:00. Pack and say goodbye to Xi'an.",
          desc_zh:"10:00前办理退房，整理行李，告别西安。",
          who:[] },
        { id:"e38", time:"10:00", type:"drive",
          title:"Leave hotel — transfer to station",       title_zh:"离开酒店——前往火车站",
          desc:"Allow extra time for luggage and getting Opa, Oma, 姥姥 & 老爷 comfortably to the platform.",
          desc_zh:"请预留充足时间处理行李，并协助爷爷、奶奶、姥姥和老爷顺利到达站台。",
          who:[] },
        { id:"e39", time:"12:00", type:"drive",
          title:"High-speed train departs — Xi'an to Beijing", title_zh:"高铁出发——西安至北京",
          desc:"Approximately 4.5 hours. Relax and reflect on a wonderful week.",
          desc_zh:"全程约4.5小时，放松身心，回味美好的一周。",
          who:[] },
        { id:"e40", time:"16:30", type:"drive",
          title:"Arrive Beijing — head home",              title_zh:"抵达北京——回家",
          desc:"Estimated arrival. Wonderful memories made — see you all again soon!",
          desc_zh:"预计抵达时间。美好回忆永存——期待大家再聚！",
          who:[] },
      ],
    },

  ], // end days

}; // end TRIP
